blog_app/urls.py
from django.urls import path
from blog_app.apps import BlogAppConfig
from blog_app.views import BlogListView, BlogCreateView, BlogDetailDetailView, \
    BlogUpdateView, BlogDeleteView

app_name = BlogAppConfig.name

urlpatterns = [
    path('create/', BlogCreateView.as_view(), name='BlogCreateView'),
    path('blog/<int:pk>', BlogDetailDetailView.as_view(),
         name='BlogDetailDetailView'),
    path('blog/', BlogListView.as_view(), name='BlogListView'),
    path('edit/<int:pk>', BlogUpdateView.as_view(), name='BlogUpdateView'),
    path('delete/<int:pk>', BlogDeleteView.as_view(), name='BlogDeleteView'),
]

catalog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from catalog.apps import CatalogConfig
from catalog.views import ContactsTemplateView, HomeListView, \
    ProductDetailView, ProductCreateView, ProductUpdateView, ProductDeleteView

app_name = CatalogConfig.name

urlpatterns = [
    path('', HomeListView.as_view(), name='HomeListView'),
    path('contacts/', ContactsTemplateView.as_view(),
         name='ContactTemplateView'),
    path('product/<int:pk>', cache_page(60)(ProductDetailView.as_view()),
         name='ProductDetailView'),
    path('create/', ProductCreateView.as_view(), name='ProductCreateView'),
    path('update/<int:pk>', ProductUpdateView.as_view(),
         name='ProductUpdateView'),
    path('delete/<int:pk>', ProductDeleteView.as_view(),
         name='ProductDeleteView'),
]

config/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.urls import path, include

urlpatterns = ([
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace='catalog')),
    path('blog/', include('blog_app.urls', namespace='blog')),
    path('users/', include('users.urls', namespace='users')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT))

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from users.apps import UsersConfig
from users.views import (RegisterView, UserUpdateView, generate_new_password,
                         ver_view)


app_name = UsersConfig.name

urlpatterns = [
    path('login/', LoginView.as_view(template_name='users/login.html'),
         name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('profile/', UserUpdateView.as_view(), name='profile'),
    path('profile/genpassword/', generate_new_password,
         name='generate_new_password'),
    path('verifying/', ver_view),

]

catalog/models.py
from django.conf import settings
from django.db import models


class Category(models.Model):
    name = models.CharField(max_length=50, verbose_name='наименование')
    description = models.TextField(verbose_name='описание')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'категория'
        verbose_name_plural = 'категории'


class Product(models.Model):
    name = models.CharField(max_length=50, verbose_name='наименование')
    description = models.TextField(verbose_name='описание')
    image = models.ImageField(upload_to='product/', verbose_name='изображение',
                              null=True, blank=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    cost = models.IntegerField(verbose_name='цена за покупку')
    date_at = models.DateTimeField(verbose_name='дата создания')
    date_last_change = models.DateTimeField(verbose_name='дата последнего '
                                                         'изменения')
    owner = models.ForeignKey(settings.AUTH_USER_MODEL,
                              on_delete=models.SET_NULL, null=True, blank=True,
                              verbose_name='пользователь')

    is_published = models.BooleanField(default=True,
                                       verbose_name='публикация активна')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'продукт'
        verbose_name_plural = 'продукты'

        permissions = [
            (
                "set_published_status",
                "Can publish product"
            )
        ]


class Version(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    number = models.IntegerField(verbose_name='номер версии')
    name = models.CharField(max_length=50, verbose_name='название версии')
    is_active = models.BooleanField(default=False,
                                    verbose_name='версия активна')

    def __str__(self):
        return f"{self.name}, {self.number}"

    class Meta:
        verbose_name = 'версия'
        verbose_name_plural = 'версии'

catalog/forms.py
from django import forms
from django.conf import settings

from catalog.models import Product, Version


class StyleFormMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class VersionForm(StyleFormMixin, forms.ModelForm):

    class Meta:
        model = Version
        fields = '__all__'


class ProductForm(StyleFormMixin, forms.ModelForm):

    class Meta:
        model = Product
        exclude = ('owner',)

    def clean_name(self):
        cleaned_data = self.cleaned_data['name']

        if cleaned_data in settings.WORDS:
            raise forms.ValidationError('Название содержит запрещённые слова')

        return cleaned_data

    def clean_description(self):
        cleaned_data = self.cleaned_data['description']

        if cleaned_data in settings.WORDS:
            raise forms.ValidationError('Описание содержит запрещённые слова')

        return cleaned_data

catalog/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin, \
    PermissionRequiredMixin
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import (TemplateView, ListView, DetailView,
                                  CreateView, UpdateView, DeleteView)
from catalog.models import Product, Version
from catalog.forms import ProductForm


class ContactsTemplateView(TemplateView):
    template_name = 'catalog/contacts.html'

    extra_context = {
        'title': 'Контакты'
    }

    @staticmethod
    def post(request):
        name = request.POST.get('name')
        phone = request.POST.get('phone')
        message = request.POST.get('message')
        print(f" {name}  {phone}  {message} ")
        return render(request, 'catalog/contacts.html')


class HomeListView(ListView):
    model = Product

    extra_context = {
        'title': 'Магазин'
    }
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['version'] = Version.objects.all()
        return context


class ProductDetailView(DetailView):
    model = Product


class ProductDeleteView(LoginRequiredMixin, DeleteView):
    model = Product
    success_url = reverse_lazy('catalog:HomeListView')


class ProductCreateView(LoginRequiredMixin, CreateView):
    model = Product
    form_class = ProductForm
    success_url = reverse_lazy('catalog:HomeListView')

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.owner = self.request.user
        self.object.save()

        return super().form_valid(form)


class ProductUpdateView(LoginRequiredMixin, PermissionRequiredMixin,
                        UpdateView):
    model = Product
    form_class = ProductForm
    permission_required = 'catalog.change_product'
    success_url = reverse_lazy('catalog:HomeListView')

catalog/templates/catalog/includes/inc_footer.html
<footer class="pt-4 my-md-5 pt-md-5 border-top">
    <div class="row">
        <div class="col-12 col-md">
            SkyStore
            <small class="d-block mb-3 text-muted">&copy; 2023</small>
        </div>
        <div class="col-6 col-md">
            <h5>Категории</h5>
            <ul class="list-unstyled text-small">
                <li><a class="text-muted" href="#">Рассылки</a></li>
                <li><a class="text-muted" href="#">Телеграм боты</a>
                </li>
                <li><a class="text-muted" href="#">Полезные утилиты</a>
                </li>
                <li><a class="text-muted" href="#">Веб-приложения</a>
                </li>
                <li><a class="text-muted" href="#">Микросервисы</a></li>
            </ul>
        </div>
        <div class="col-6 col-md">
            <h5>Дополнительно</h5>
            <ul class="list-unstyled text-small">
                <li><a class="text-muted" href="#">Мы пишем</a></li>
            </ul>
        </div>
        <div class="col-6 col-md">
            <h5>О нас</h5>
            <ul class="list-unstyled text-small">
                <li><a class="text-muted"
                       href="{% url 'catalog:ContactTemplateView' %}">Контакты</a>
                </li>
            </ul>
        </div>
    </div>
</footer>

catalog/templates/catalog/includes/inc_menu.html
<div class="d-flex flex-column flex-md-row align-items-center
        p-3 px-md-4 mb-3 bg-white border-bottom box-shadow">
    <h5 class="my-0 mr-md-auto font-weight-normal">Магазин и Блог</h5>
    <nav class="ms-8">

        {% if user.is_authenticated %}

        <a class="p-2 btn btn-outline-primary"
           href="{% url 'users:logout' %}">Выйти</a>

        <a class="p-2 btn btn-outline-primary"
           href="{% url 'users:profile' %}">Профиль</a>

        {% else %}

        <a class="p-2 btn btn-outline-primary"
            href="{% url 'users:login' %}">Войти</a>
        <a class="p-2 btn btn-outline-primary"
            href="{% url 'users:register' %}">Регистрация</a>


        {% endif %}

        <p></p>
        <a class="p-2 btn btn-outline-primary"
           href="{% url 'catalog:HomeListView' %}">Магазин электроники</a>
        <a class="p-2 btn btn-outline-primary"
           href="{% url 'blog:BlogListView' %}">Блог</a>
        <a class="p-2 btn btn-outline-primary"
           href="{% url 'catalog:ContactTemplateView' %}">Контакты</a>
    </nav>
</div>