blog_app/urls.py
from django.urls import path
from blog_app.apps import BlogAppConfig
from blog_app.views import BlogListView, BlogCreateView, BlogDetailDetailView, \
    BlogUpdateView, BlogDeleteView

app_name = BlogAppConfig.name

urlpatterns = [
    path('create/', BlogCreateView.as_view(), name='BlogCreateView'),
    path('blog/<int:pk>', BlogDetailDetailView.as_view(),
         name='BlogDetailDetailView'),
    path('blog/', BlogListView.as_view(), name='BlogListView'),
    path('edit/<int:pk>', BlogUpdateView.as_view(), name='BlogUpdateView'),
    path('delete/<int:pk>', BlogDeleteView.as_view(), name='BlogDeleteView'),
]

config/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.urls import path, include

urlpatterns = ([
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace='catalog')),
    path('blog/', include('blog_app.urls', namespace='blog')),
    path('users/', include('users.urls', namespace='users')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT))

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from users.apps import UsersConfig
from users.views import (RegisterView, UserUpdateView, generate_new_password,
                         ver_view)


app_name = UsersConfig.name

urlpatterns = [
    path('login/', LoginView.as_view(template_name='users/login.html'),
         name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('profile/', UserUpdateView.as_view(), name='profile'),
    path('profile/genpassword/', generate_new_password,
         name='generate_new_password'),
    path('verifying/', ver_view),

]

blog_app/models.py
from django.db import models


class Blog(models.Model):
    title = models.CharField(max_length=150, verbose_name='заголовок')
    content = models.TextField(verbose_name='содержимое')
    preview = models.ImageField(upload_to='blog_app/', verbose_name='превью',
                                null=True, blank=True)
    date_of_creation = models.DateTimeField(verbose_name='дата создания')

    view_count = models.IntegerField(default=0, verbose_name='просмотры')
    is_published = models.BooleanField(default=True,
                                       verbose_name='опубликовано')
    slug = models.CharField(max_length=150, verbose_name='slug', null=True,
                            blank=True)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'блог'
        verbose_name_plural = 'блоги'

blog_app/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy, reverse
from django.views.generic import ListView, CreateView, DetailView, UpdateView, \
    DeleteView
from pytils.translit import slugify
from blog_app.models import Blog


class BlogCreateView(LoginRequiredMixin, CreateView):
    model = Blog
    fields = ('title', 'content', 'date_of_creation')
    success_url = reverse_lazy('blog:BlogListView')

    def form_valid(self, form):
        if form.is_valid:
            new_blog = form.save()
            new_blog.slug = slugify(new_blog.title)
            new_blog.save()

        return super().form_valid(form)


class BlogDetailDetailView(DetailView):
    model = Blog

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        self.object.view_count += 1
        self.object.save()
        return self.object


class BlogListView(ListView):
    model = Blog
    extra_context = {
        'title': 'Блог'
    }

    def get_queryset(self, *args, **kwargs):
        queryset = super().get_queryset(*args, **kwargs)
        queryset = queryset.filter(is_published=True)
        return queryset


class BlogUpdateView(LoginRequiredMixin, UpdateView):
    model = Blog
    fields = ('title', 'content', 'date_of_creation', 'preview')

    def form_valid(self, form):
        if form.is_valid:
            new_blog = form.save()
            new_blog.slug = slugify(new_blog.title)
            new_blog.save()

        return super().form_valid(form)

    def get_success_url(self):
        return reverse('blog:BlogDetailDetailView',
                       args=[self.kwargs.get('pk')])


class BlogDeleteView(LoginRequiredMixin, DeleteView):
    model = Blog
    success_url = reverse_lazy('blog:BlogListView')

blog_app/templates/blog_app/blog_confirm_delete.html
{% extends 'catalog/base.html' %}

{% block content %}
<div class="col-12">
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        <p>Хотите удалить блог "{{ object.title }}
                            {{ object.date_of_creation }}" ?</p>
                        <button type="submit" class="btn btn-da">
                            Подтвердить
                        </button>
                        <a href="{% url 'blog:BlogListView' %}"
                           class="btn btn-warning">Отмена</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

blog_app/templates/blog_app/blog_detail.html
{% extends 'catalog/base.html' %}
{% block content %}
<div class="col-12">
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">
                        Информация о блоге
                    </h3>
                </div>
                <div class="card-body">
                    <table class="table">
                        <tr>
                            <td>Заголовок</td>
                            <td>{{ object.title }}</td>
                            <td>{{ object.slug }}</td>
                        </tr>
                        <tr>
                            <td>Содержимое</td>
                            <td>{{ object.content }}</td>
                        </tr>
                        <tr>
                            <td>Дата создания</td>
                            <td>{{ object.date_of_creation }}</td>
                        </tr>
                    </table>
                </div>
                <div class="card-footer"></div>
                Просмотры: {{ object.view_count }}
            </div>
        </div>
        <div class="col-6">
            <img src="/media/{{ object.preview }}"/>
        </div>
    </div>
</div>
{% endblock content %}

blog_app/templates/blog_app/blog_form.html
{% extends 'catalog/base.html' %}
{% block content %}
<div class="col-12">
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-body">
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form.as_p }}
                        {% if object %}
                        <button type="submit" class="btn btn-primary">Изменить
                        </button>
                        {% else %}
                        <button type="submit" class="btn btn-primary">Создать
                        </button>
                        {% endif %}
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

blog_app/templates/blog_app/blog_list.html
{% extends 'catalog/base.html' %}
{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">{{ title }}</h1>
</div>
<div class="container">
    <div class="row text-center">
        <div class="col-12 mb-5">
            <a class="btn btn-outline-primary"
               href="{% url 'blog:BlogCreateView' %}">Добавить блог</a>
        </div>
        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
            {% for object in object_list %}
            <div class="col-md-6">
                <div class="card mb-4 box-shadow">
                    <div class="card-body">
                        <p class="card-text">{{ object.title }}</p>
                        <p class="card-text">{{ object.content }}</p>
                        <div class="d-flex justify-content-between align-items-center">
                            <div class="btn-group">
                                <a href="{% url 'blog:BlogDetailDetailView' object.pk %}"
                                   class="btn btn-sm btn-outline-secondary">
                                    Посмотреть
                                </a>
                                <a href="{% url 'blog:BlogUpdateView' object.pk %}"
                                   type="button"
                                   class="btn btn-sm btn-outline-secondary">
                                    Изменить
                                </a>
                                <a href="{% url 'blog:BlogDeleteView' object.pk %}"
                                   type="button"
                                   class="btn btn-sm btn-outline-secondary">
                                    Удалить
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock content %}