catalog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from catalog.apps import CatalogConfig
from catalog.views import ContactsTemplateView, HomeListView, \
    ProductDetailView, ProductCreateView, ProductUpdateView, ProductDeleteView

app_name = CatalogConfig.name

urlpatterns = [
    path('', HomeListView.as_view(), name='HomeListView'),
    path('contacts/', ContactsTemplateView.as_view(),
         name='ContactTemplateView'),
    path('product/<int:pk>', cache_page(60)(ProductDetailView.as_view()),
         name='ProductDetailView'),
    path('create/', ProductCreateView.as_view(), name='ProductCreateView'),
    path('update/<int:pk>', ProductUpdateView.as_view(),
         name='ProductUpdateView'),
    path('delete/<int:pk>', ProductDeleteView.as_view(),
         name='ProductDeleteView'),
]

config/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.urls import path, include

urlpatterns = ([
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace='catalog')),
    path('blog/', include('blog_app.urls', namespace='blog')),
    path('users/', include('users.urls', namespace='users')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT))

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from users.apps import UsersConfig
from users.views import (RegisterView, UserUpdateView, generate_new_password,
                         ver_view)


app_name = UsersConfig.name

urlpatterns = [
    path('login/', LoginView.as_view(template_name='users/login.html'),
         name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('profile/', UserUpdateView.as_view(), name='profile'),
    path('profile/genpassword/', generate_new_password,
         name='generate_new_password'),
    path('verifying/', ver_view),

]

catalog/models.py
from django.conf import settings
from django.db import models


class Category(models.Model):
    name = models.CharField(max_length=50, verbose_name='наименование')
    description = models.TextField(verbose_name='описание')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'категория'
        verbose_name_plural = 'категории'


class Product(models.Model):
    name = models.CharField(max_length=50, verbose_name='наименование')
    description = models.TextField(verbose_name='описание')
    image = models.ImageField(upload_to='product/', verbose_name='изображение',
                              null=True, blank=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    cost = models.IntegerField(verbose_name='цена за покупку')
    date_at = models.DateTimeField(verbose_name='дата создания')
    date_last_change = models.DateTimeField(verbose_name='дата последнего '
                                                         'изменения')
    owner = models.ForeignKey(settings.AUTH_USER_MODEL,
                              on_delete=models.SET_NULL, null=True, blank=True,
                              verbose_name='пользователь')

    is_published = models.BooleanField(default=True,
                                       verbose_name='публикация активна')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'продукт'
        verbose_name_plural = 'продукты'

        permissions = [
            (
                "set_published_status",
                "Can publish product"
            )
        ]


class Version(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    number = models.IntegerField(verbose_name='номер версии')
    name = models.CharField(max_length=50, verbose_name='название версии')
    is_active = models.BooleanField(default=False,
                                    verbose_name='версия активна')

    def __str__(self):
        return f"{self.name}, {self.number}"

    class Meta:
        verbose_name = 'версия'
        verbose_name_plural = 'версии'

catalog/forms.py
from django import forms
from django.conf import settings

from catalog.models import Product, Version


class StyleFormMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class VersionForm(StyleFormMixin, forms.ModelForm):

    class Meta:
        model = Version
        fields = '__all__'


class ProductForm(StyleFormMixin, forms.ModelForm):

    class Meta:
        model = Product
        exclude = ('owner',)

    def clean_name(self):
        cleaned_data = self.cleaned_data['name']

        if cleaned_data in settings.WORDS:
            raise forms.ValidationError('Название содержит запрещённые слова')

        return cleaned_data

    def clean_description(self):
        cleaned_data = self.cleaned_data['description']

        if cleaned_data in settings.WORDS:
            raise forms.ValidationError('Описание содержит запрещённые слова')

        return cleaned_data

catalog/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin, \
    PermissionRequiredMixin
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import (TemplateView, ListView, DetailView,
                                  CreateView, UpdateView, DeleteView)
from catalog.models import Product, Version
from catalog.forms import ProductForm


class ContactsTemplateView(TemplateView):
    template_name = 'catalog/contacts.html'

    extra_context = {
        'title': 'Контакты'
    }

    @staticmethod
    def post(request):
        name = request.POST.get('name')
        phone = request.POST.get('phone')
        message = request.POST.get('message')
        print(f" {name}  {phone}  {message} ")
        return render(request, 'catalog/contacts.html')


class HomeListView(ListView):
    model = Product

    extra_context = {
        'title': 'Магазин'
    }
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['version'] = Version.objects.all()
        return context


class ProductDetailView(DetailView):
    model = Product


class ProductDeleteView(LoginRequiredMixin, DeleteView):
    model = Product
    success_url = reverse_lazy('catalog:HomeListView')


class ProductCreateView(LoginRequiredMixin, CreateView):
    model = Product
    form_class = ProductForm
    success_url = reverse_lazy('catalog:HomeListView')

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.owner = self.request.user
        self.object.save()

        return super().form_valid(form)


class ProductUpdateView(LoginRequiredMixin, PermissionRequiredMixin,
                        UpdateView):
    model = Product
    form_class = ProductForm
    permission_required = 'catalog.change_product'
    success_url = reverse_lazy('catalog:HomeListView')

catalog/templates/catalog/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Skystore</title>
    <link href="/catalog/static/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
{% include 'catalog/includes/inc_menu.html' %}

{% block content %}
{% endblock content %}

{% include 'catalog/includes/inc_footer.html' %}

<script src="/catalog/static/js/bootstrap.bundle.min.js"></script>
</body>
</html>

catalog/templates/catalog/contacts.html
{% extends 'catalog/base.html' %}

{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">{{ title }}</h1>
</div>

<div class="container">
    <div class="row text-start">
        <div class="col-lg-9 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-body">
                    <table class="table table-striped">
                        <tr>
                            <td class="w-25">Страна</td>
                            <td>USA</td>
                        </tr>
                        <tr>
                            <td class="w-25">ИНН</td>
                            <td>91-1144442</td>
                        </tr>
                        <tr>
                            <td class="w-25">Адрес</td>
                            <td>Redmond,WA,98052-6399</td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
        <div class="col-lg-3 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">Свяжитесь с нами</h4>
                </div>
                <div class="card-body">
                    <form method="post" action="" class="form-floating">
                        {% csrf_token %}
                        <div class="mb-3">
                            <label for="name">Имя</label>
                            <input type="text" name="name" class="form-control"
                                   id="name" placeholder="Ваше имя" required>
                        </div>
                        <div class="mb-3">
                            <label for="phone">Телефон</label>
                            <input type="text" name="phone" class="form-control"
                                   id="phone" placeholder="Контактный телефон"
                                   required>
                        </div>
                        <div class="mb-3">
                            <label for="message">Сообщение</label>
                            <textarea name="message"
                                      class="form-control" id="message"
                                      placeholder="Сообщение"
                                      required></textarea>
                        </div>
                        <button type="submit"
                                class="btn btn-lg btn-block btn-outline-primary">
                            Отправить
                        </button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

catalog/templates/catalog/product_confirm_delete.html
{% extends 'catalog/base.html' %}

{% block content %}

<div class="col-12">
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        <p>Хотите удалить продукт "{{ object.name }}" ?</p>
                        <button type="submit" class="btn btn-da">
                            Подтвердить
                        </button>
                        <a href="{% url 'catalog:HomeListView' %}"
                           class="btn btn-warning">Отмена</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock content %}

catalog/templates/catalog/product_detail.html
{% extends 'catalog/base.html' %}
{% load my_tags %}

{% block content %}

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">{{ title }}</h1>
</div>

<div class="container">
    <div class="row text-start">
        <div class="col-lg-12 col-md-12 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-body">
                    <table class="table table-striped">
                        <div class="card" style="width: 18rem;">
                            <img src="{{ product.image|mediapath }}">
                            <div class="card-body">
                                <h5 class="card-title">{{ title }}</h5>
                                <p class="card-text">Название товара:
                                    {{product.name }}</p>
                                <p class="card-text">Описание товара:
                                    {{product.description }}</p>
                                <p class="card-text">Категория товара:
                                    {{product.category }}</p>
                                <p class="card-text">Стоимость товара:
                                    {{product.cost }}</p>
                                <p class="card-text">Дата создания:
                                    {{product.date_at }}</p>
                                <p class="card-text">Дата изменения:
                                    {{product.date_last_change }}</p>
                            </div>
                        </div>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

catalog/templates/catalog/product_form.html
{% extends 'catalog/base.html' %}

{% block content %}

<div class="col-12">
    <form class="row" method="post" enctype="multipart/form-data">
        <div class="col-6">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">
                        Добавление продукта
                    </h3>
                </div>
                <div class="card-body">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-success">
                        Сохранить
                    </button>
                </div>
            </div>
        </div>
    </form>
</div>

{% endblock content %}

catalog/templates/catalog/product_list.html
{% extends 'catalog/base.html' %}

{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">{{ title }}</h1>
</div>

<div class="container">
    <div class="row text-center">
        <div class="col-12 mb-3">
            <a class="btn btn-outline-primary"
               href="{% url 'catalog:ProductCreateView' %}">
                Добавить продукт </a>
        </div>
        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-2 g-2">
            {% for object in object_list %}
            <div class="col">
                <div class="card shadow-sm">
                    <div class="card-body">
                        <p class="card-text">
                            {{ object.name }}

                        <p class="card-text">
                            {{ object.description|truncatechars:100 }}</p>
                        <span class="text-muted">
                                    {{ object.owner|default:'пользователь отсутствует' }}</span>
                        <div class="d-flex justify-content-between align-items-center">
                            <div class="btn-group">
                                <a class="btn btn-sm btn-outline-secondary"
                                   href="{% url 'catalog:ProductDetailView' object.pk %}">
                                    Посмотреть
                                </a>
                                <a class="btn btn-sm btn-outline-secondary"
                                   href="{% url 'catalog:ProductUpdateView' object.pk %}">
                                    Изменить
                                </a>
                                <a class="btn btn-sm btn-outline-secondary"
                                   href="{% url 'catalog:ProductDeleteView' object.pk %}">
                                    Удалить
                                </a>
                            </div>
                        </div>
                        <p>
                            {% for version in object.version_set.all %}
                            {% if version.is_active %}
                            Номер версии - {{ version.number }}
                            <br>
                            Название версии - {{ version.name }}
                            {% endif %}
                            {% endfor %}
                        </p>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock content %}